# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'KAWAI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KAWAI
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Hero'
  pod 'PageMenu'


  target 'KAWAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KAWAIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
